apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ai-env
  namespace: wallet
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: woori-wallet-ssm
    kind: ClusterSecretStore
  target:
    name: ai-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        .env: "{{ .aiEnv }}"
  data:
    - secretKey: aiEnv
      remoteRef:
        key: /woori-wallet/prod/trial/ai-env
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
