apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: metrics-token
  namespace: woori
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: woori-wallet-ssm
    kind: ClusterSecretStore
  target:
    name: metrics-token
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: METRICS_TOKEN
      remoteRef:
        key: /woori-wallet/prod/metrics-token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
