apiVersion: v1
kind: Service
metadata:
  name: wallet-backend
  namespace: wallet
  labels:
    app.kubernetes.io/name: wallet-backend
    app.kubernetes.io/part-of: woori-wallet
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wallet-backend
  ports:
    - name: http
      port: 80
      targetPort: http
