apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: woori-wallet-ssm
  labels:
    app.kubernetes.io/name: woori-wallet-ssm
    app.kubernetes.io/part-of: woori-wallet
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
