apiVersion: v1
kind: Service
metadata:
  name: wallet-ai
  namespace: wallet
  labels:
    app.kubernetes.io/name: wallet-ai
    app.kubernetes.io/part-of: woori-wallet
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wallet-ai
  ports:
    - name: http
      port: 8002
      targetPort: http
