apiVersion: v1
kind: Service
metadata:
  name: woori-db
  namespace: woori
  labels:
    app.kubernetes.io/name: woori-db
    app.kubernetes.io/part-of: woori-wallet
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: woori-db
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
